### ISSUE TITLE
建议去除一些后备字形

### ISSUE THREAD

**Issue by 747** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project#11]
![image](https://user-images.githubusercontent.com/3427854/224049415-17e551c8-3be4-4ffa-8508-bbe561eb7789.png)

只存在占位字形的下列字符，如果无意支持的话应该从字体里删除，或补入正确字形。它们只是普通的标点符号，不属于`Default_Ignorable_Code_Point`，因此渲染器不会自动掩蔽字形，字符混入时导致显示效果不佳。比如：

> `No. 1` (U+004E U+006F U+002E U+00A0 U+0031)
> ![image](https://user-images.githubusercontent.com/3427854/224051917-32555be0-4c40-4dd9-ad57-9d64bede1856.png)

|Codepoint|Name|
|:-:|:-|
|U+00A0|NO-BREAK SPACE|
|U+2000|EN QUAD|
|U+2001|EM QUAD|
|U+2002|EN SPACE|
|U+2003|EM SPACE|
|U+2004|THREE-PER-EM SPACE|
|U+2005|FOUR-PER-EM SPACE|
|U+2006|SIX-PER-EM SPACE|
|U+2007|FIGURE SPACE|
|U+2008|PUNCTUATION SPACE|
|U+2009|THIN SPACE|
|U+200A|HAIR SPACE|
|U+2011|NON-BREAKING HYPHEN|
|U+202F|NARROW NO-BREAK SPACE|
|U+205F|MEDIUM MATHEMATICAL SPACE|

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
首先，感谢您关注本项目。
您在上文中所提到的这些字符，对于我本人来说均有特殊用途，因而制作成了上图的样式，因此，这些字符本人不会去删除，您可尝试使用将这些字符删除后所生成的改版字体，给您带来的不便敬请谅解。
另外，上图中的字体似乎是旧版本，新版本中这些字符全部都进行了修整，强烈建议使用新版本字体。
