### ISSUE TITLE
字体版本号问题

### ISSUE THREAD

**Issue by OpportunityLiu** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project#14]
请问本字体版本号是如何定义的？为什么两个字体文件以及 GitHub 的 tag 版本均不同？

![image](https://user-images.githubusercontent.com/13471233/237047910-97b41291-79d1-4de2-9d44-fed5956c5703.png)

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
字体版本号是根据每一次的字符改动量而决定的，因此P1和P2字体各自的版本号并不相同。
Release版中的版本号则是将二者的版本号相加而得。
字体文件内的版本号只能填写小数点前1位和后3位，因此字体文件名上的版本号无法一模一样的填入到字体文件内，文件名上所标注的版本号为正确的。
