### ISSUE TITLE
发现一些可改善的地方（未完待续）

### ISSUE THREAD

**Issue by MY1L** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project#15]
我听说源文件字形个别是三次曲线，不过拿到手的是ttf，所以不清楚是否三转二导致了问题。

检查了 Plangothic P1.fallback : 6.397版（20230613）有如下问题：

- [ ] 控制图符，可从[Ctrl Ctrl](https://github.com/MY1L/Ctrl/releases/tag/Ctr1)和[Monu Temp](https://github.com/MY1L/Unicode/releases/tag/Temp)（统一码16版）复制粘贴。
- [ ] “A0117”⿰贝亅 u2EDBE像没做完似的，可从[Monu Temp]复制粘贴。
- [x] u2EE4A 曲线重复，疑似重复粘贴了2次。
- [ ] 由于是挨个手动修复曲线才发现问题越来越多，忘记自己已修过了哪些，这些字形在我印象中存在问题：u2EC04 u2ED4D u2EDB9，会导致fontmake报错。
- [ ] 这些字形皆为曲线报错导致合并故障，某些是曲线反向了，我没有一个个查：u2EC26 u2EC3D u2EC59 u2EC65 u2EC6A u2EC6B u2EC6C u2EC6D u2EC6E u2EC6F u2EC73 u2EC74 u2EC75 u2EC76 u2EC8D u2ECD8 u2ECF0 u2ED15 u2ED22 u2ED34 u2ED47 u2ED6B u2ED75 u2ED7A u2ED7D u2ED81 u2ED82 u2ED85 u2ED86 u2ED8A u2ED8D u2ED92 u2ED98 u2EDA1 u2EDE6 u2EE0E u2EE10 u2EE18 u2EE31 
- [ ] uF23D字证显示应是“⿰X也”而非“⿰乂也”。
- [ ] 1AFF0假名扩乙曲线质量不佳，可从[Ctrl Kana]复制粘贴。
- [ ] u1B108笔顺不对，可从[Ctrl Kana]复制粘贴。
- [ ] u2EDFF明显难看。

(只抽样检查了汉字扩壬区段，尚未看完（另2个字体还没看），待更新)

[Ctrl Kana]:https://github.com/MY1L/Ctrl/releases/tag/Kana
[Monu Temp]:https://github.com/MY1L/Unicode/releases/tag/Temp

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
抱歉，我好像误触了什么东西，第一条没了（扶额），你加一下。
逐条回答一下：
1. 关于控制字符的问题，你可以看得出来我是择取了一部分，但没有全择取，因为那些没择地方不太符合我的意愿。
2. 曲线重复问题已经修复，下个版本会跟进。
3. 曲线反向问题的来源是隙间黑体，属于早期遗物，因目前精力有限，暂无法进行逐字检查。
4. 关于`U+F23D`，字证确实是`⿰X也`不假，但是不能那么做，因为得体现的像汉字一些。
5. 关于你所制作的`变态假名`，不符合本项目的风格，暂时不打算择取。
6. 因为目前这个项目被大厂字体制约的越来越严重（主要体现在普惠和中黒），现在的目标是以补全所有汉字为主，补全之后再进行修缮。

**Comment by MY1L** [comment]
Plangoth.P1 fb. 6.397版的控制图符，我理解你是想让虚线框更“虚”，但这个虚框锚点太密比较占文件体积和渲染。
不过，影响美观的问题在替换的西文字重不一致，在实际使用中，那些3字控制图符字距挤到笔画粘连，且圆形笔画不圆（怀疑是缩小、三转二取整导致锚点偏移）。我作控制图符里西文是专门设计避免这些问题的。
![image](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/cb05d7a1-1569-4291-afa8-6785ada9d65b)
u00A0 u00AD……这几个不太理解，是必须这么挤着设计吗，如果个人用途上是必须的话，何不旋转90°竖排，抽掉虚线框的横向虚线段落而非挤压。

----

u1B108 u1AFF5等问题，观察统一码原图可发现是写法不对，影响到使用，不是风格的差异。

还没说Pg1f.…6.397版变体假名风格各有差异，目测可以分成两三组（u1B069 u1B07F……一组，u1B06A u1B072……又一组，u1B043……甚至是2组混合），u1AFF9 u1AFFA字重明显不同。由于只是风格差异无所谓我就没提，只是如果将来重制不知应以哪组为准。
话说笔画等宽看不清影响到实用性。变体假名设计可参考同字体的平假名，不用说思源黑平假名（如“ゑ”）的笔画不是等宽的，思源黑汉字笔画也不是等宽的呀。

----

关于⿰贝亅，其间架参照思源黑的“刂刊刘利㓚㺫”可对比。“贝”也不是不能变窄，只是显得空一块。我觉得那些形如“则”缺笔状字证都是因为没人设计字体所以没办法的妥协，并不是出于美感的设计。现在是它第一次不需要妥协了。

----

关于⿰X也，我只觉得字形太奇怪了，见思源黑的“刈䖊赵”的丶也没这么短，不知是怎么做出来的，打这段字时发现雅黑的刈的丿和丶是几乎同长。看了〤〷ㄨ㐅乂，如果只是为了“像汉字一些”，那么可以拆像汉字的“〷”的左半用。

题外话，这个“像汉字”符号算不算汉字呢，何不视作是像“㋆”一样的符号来制作？看着用途更接近🈀🈁🉠㈤㉮㋿……是否可以考虑向统一码提议放到1F200..区段里。

----

关于输出三次曲线字体文件会损毁的问题恐怕是不好解决。字体版本号处写了“Version 6.397;June 13, 2023;**FontCreator 14**.0.0.2901 64-bit”，我没这个版本，就看了下旧版FC对u2EC04的曲线用红点标记了一些会导致三次曲线输出故障的地方。
![image](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/b53433b8-f9ac-454c-b109-316fe8ec62b0)
接头处放大32000%可见谜之锐角，这里除了影响合并还会导致某些adobe软件“爆刺”：
![image](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/cea83881-e902-4642-ad25-7124abaf69a7)
类似这样的奇怪接头感觉是三转二取整导致锚点偏移，得看下源文件是什么情况。
![image](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/9aed4399-27da-494b-be82-f33aa4a90690)

先写到这。

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
1. 关于`U+00A0`，`U+00AD`，因为思源黑体中已经给定了这两个字符的宽度，加之这两个字符在Unicode中带有虚线框（我姑且先这么称呼之），所以便设计成这个样子，暂时不会对其更改。
2. 遍黑体里面`变态假名`总共分了三次进行制作，三次的时间跨度较大，所以出现了风格不统一的情况，我的合作人[Siphercase](https://github.com/Siphercase)在不久前提到説他要对`变态假名`进行重置，但目前似乎也没消息，有关`变态假名`的写法也是亟待商讨的一个问题之一，目前遍黑体的权重放在汉字上，`变态假名`等到所有的汉字补充完毕后再考虑修缮。
3. `⿰贝亅`和`⿰X也`我权且保留意见。WS2021中对`⿰X也`给的IDS是`⿰㐅也`，字工具给出的IDS是`⿰乂也`，我个人认为使用`〷`不妥，既然它能出现在WS2021中，那就得按照汉字去对待。
4. 毛刺同样也是老问题，因目前精力有限，暂无法进行逐字检查。
