### ISSUE TITLE
合并p1 p2

### ISSUE THREAD

**Issue by hemoumouda** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project#17]
可不可以考虑吧p1和p2合并成一个ttc文件?

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
这是一个好主意，早些时候我确实有此想法，但是苦于我不会也不知道如何合并，请问您有什么好的方法吗？

**Comment by hemoumouda** [comment]
可以使用Adobe Font Development Kit，通过以下方式安装它
1.安装Python(版本≥3.8,推荐使用3.8版本。因为稳定)。
2.在命令提示符中输入`pip install afdko`并回车。
3.等待安装过后输入`otf2otc -o [输出文件名称] [字体1] [字体2] …… [字体n] `即可合成ttc文件。

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
感谢方法建议，在下一版本的时候我会试一试。

**Comment by ungtl** [comment]
> 感谢方法建议，在下一版本的时候我会试一试。

也可以使用FontForge先打开要合并的全部字体，然后点击左上角的 “文件” 选项，第十行有一个 “生成TTC...” 选项，然后点击 “Generate” 选项，也可以合并为TTC字体。
