### ISSUE TITLE
攒了一波问题，以及其解决（P1 0.6.3980，P2 1.2.1767）

### ISSUE THREAD

**Issue by MY1L** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project#18]
来不及整理了，以流水账形式：
### P1 0.6.3980
u2FFF“⿿”、u1B11F~1B122假名扩甲的曲线质量差。
![](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/6765f0be-39c9-4b81-afd9-6a25756faccf)![](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/108ad0b3-57ab-4697-803f-8344c7e69031 "这是怎么做出来的？")
- [x] 我已原创或制作了字形。

u31EF“㇯”的含义似乎不对，意思是从某字(虚线框)减去内部的一块(虚线框)，而非减去某字(虚线框)。
- [x] 我已原创了字形。

汉文训读的字重过细。
- 已聊过。或有折衷的方案：粗的同时字面小一点，靠近上标。

私用区字形应有说明以解释用途。
- 已聊过。我觉得是个问题。

假名扩乙曲线质量很差，弧线如折线，笔画不匀，或写错了（如𚿵不是一根竖杠，𚿽不是一根竖杠加圆圈）、字重太细（提案中𚿺𚿾不是类似标点﹅﹆的空心形式，是正常笔画）
- [x] [我已原创了字形。](https://user-images.githubusercontent.com/58043328/219873654-72073f1e-6c9c-4c60-ac24-4ba720b88035.png)

麻将字形相对汉字过小，象棋也是，且偏细。
- 继承NotoSym的美术问题吧……

运行字体检验向导（不勾选标*项、不勾选离极点检查）仅检查61440个汉字，发现有40607个字形有各式各样的问题。如：u20003在直线内有多余的锚点，u20007等7918个字形的曲线含负形（全体或部分方向反了，难修，尽量吧），u4695等4078个字形锚点重叠，u70AD有锐利奇点，u200D5等34个字形有孤立锚点（或造成故障强烈建议修复），u20181等74个字形重叠了2层（造成冗余建议修复）
- 已聊过。我将解决其中一部分。
- [x] 其中k奇葩C类，我已原创或修改了𠆭𠪳𢀓𬻷𬻿𬼂𭅃𭍻𭑊𭚥𭤪𭥟𮓠𮥹（详见[统一码C类奇葩汉字](https://www.bilibili.com/read/cv27511908/)，附[源文件MonuHanS](https://github.com/MY1L/Unicode/blob/main/Hani/note.md#han2)）

尚未解决：𠇇，尤其𭁇曲线质量差应当修改，但我不确定怎么做美观还没搞。做成ま形？
![](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/6e9f6f86-c8da-4128-b0b0-117f977ecc4f "这又是怎么做出来的？")

上述曲线反向中需着重修正的！
1. u211A2
2. u219D1
3. u22013
4. u2CEF7
5. u2CEFF
6. u2CF02
7. u2D37B
8. u2D6A5
9. u2D95F
10. u2E4E0

合略仮名𪜈(トモ)𬼀(シテ)问题。尤其𪜈似应按仮名制作，1.这些字形没指望与汉字搭配，2.𪜈有浊点形式，没勾，不是汉字。
- [x] 我已原创或制作了字形。

### Part2 1.2.1767
E0001起的标签区段里的“标签”字形是否是开源的？
- [x] 我已原创了字形。

其它非汉字应该有问题但没检查，已知NotoArab存在错误，不过遍黑似乎也不用支持非方块字的……

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
# ①U+2FFF“⿿”、②U+31EF“㇯”
目前的Release最新版的遍黑体中，这两个形态已经弃用了，下个版本会跟进成和码表相同，即如此：
![QQ截图20231107211701](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/82664718/a4b5d416-ceb1-4ffd-a2a0-15087f84771d)![QQ截图20231107211857](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/82664718/fa45eec6-ed63-4e74-a5b2-8f03e49e8351)
两个形态均择自[隙间黑体](https://oppekebekkanko.booth.pm/items/2117070)。
考虑到你的字体对这两个字符所制作的样式与我的字体风格差异较大，故不采用。
# ③汉文训读的字重过细
根据姜兆勤（Kushim Jiang）的说法，汉文训读不该做成上标的形态，因此在下一版本中，汉文训读的所有字符全部删除。
# ④私用区字形应有说明以解释用途
之前有加过，但被[Hulenkius](https://github.com/Hulenkius)指出属于添加冗余信息而被他删除之，本人亦同意他的决策。
# ⑤假名拡张B
因为我不了解变态假名拡张B，因而呈现出目前的形态，如果有足够的证据可以证明你的说法，则会将你所制作的合入我的字体项目里。
**PS: 假名拡张B非本人制作。**
# ⑥麻将字形、象棋字形
麻将的字形直接放大自Noto Sans Symbols，除此之外其他方面均不会做任何改动。
象棋的字形目前无暇进行修整操作。
# ⑦KStrange - Cursive
这里要提到遍黑体的一个规则：
> 不看汉字的来源，只要它被收录进汉字区块，就要按照汉字的规则去看待。

也就是說，这里面只有`U+201AD，𠆭`、`U+20AB3，𠪳`、`U+22013，𢀓`、`U+2CEFF，𬻿`、`U+2D95F，𭥟`可以从你的字体里择出。
与我参与制作遍黑体项目的成员普遍都没有绘制曲线的能力，所以才会出现这样的情况。
曲线反向的问题目前无暇进行修整操作。
# ⑧P2标签区块
该区块下的所有字符均由本人进行过重绘，拉丁字母择自Noto Sans。

**Comment by MY1L** [comment]
我今天终于解决了𠇇𭁇的曲线，并稍微调了𠆭𭥟等字的字形，笔画拆分源文件稍后随MonuHani9.6说明更新放出，[而字体本身已经可下载了](https://github.com/MY1L/Unicode/releases/tag/Hani9)，并附我做的许多兼容区汉字字形，某些字与统一码相差一两笔，具体清单已写，待一并更新。
字形应当有清单以便管理，不论对制作者自己还是对使用者。

实际使用中，纯文本内麻将或绘文字的字形似乎放大到120~140%才能显得与汉字差不多大。老实说如果是单独一个彩色麻将字体，改upm比改字形本身更好。

假名扩乙遵循此提案的最终版：https://www.unicode.org/L2/L2020/20209r-taiwan-kana.pdf，直接跳到Chapter 4 Evidence of all requested characters——我干脆截屏吧：
![image](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/8a0a98e3-73aa-43eb-bdfb-92da7f5cb74a)这张图同时呈现了竖杠和𚿵，即便扫图很渣也能显出𚿵不是根竖杠。
𚿷𚿸𚿹𚿺𚿻𚿽𚿾这一列划圈符号是与𚿰𚿱𚿲𚿳𚿵𚿶一一对应的鼻音，它们实际都是一笔画以书写，并非印刷预置符号（即“𚿺𚿾不是𚿲𚿶的空心形式”）
![image](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/0b7d8ab7-3445-4cf0-89b2-783180633f78)![image](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/87059ce1-e635-4d79-a52e-c297b57ea799)

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
- KStrange：你所改的字部分采用，`𠇇𭁇`我个人觉得曲笔部分应该垂直下去，不应该打弯。**
![QQ截图20231125202424](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/82664718/1f85a5cc-4892-4fc7-b37c-50847915e090)
- 兼容字：不采用，遍黑体中的兼容字々形跟IRG成员核对过，既符合兼容的特性，又符合假想陆标。
- 私用区字形清单问题：看其他人的想法，如果呼声较高则采纳（其实之前有列，但后来被其他的协作者删了，认为无用）。
- 麻将：暂不考虑，因为这些字符某种意义上可以属于凑数行列。
- 假名拡张B：我需要知道一点，就是书证上所呈现的假名确定不是为了符合宋体（衬线体）而在字形设计风格层面的变动吗？如果不是，则确乎是可以采用你的字形。

**Comment by MY1L** [comment]
这个弯曲只是视错觉修正，实际使用中，比如github这个字号下看上去是直的。大多黑体有类似这样设计，不提西文，在汉字中常见于竖钩笔画，其右侧不垂直。
比如看2个系统默认字体，微软雅黑的“丁丙则”：
![丁](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/6244a172-4307-4158-b932-c014d9779697)![丙](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/9003863b-14b2-4206-99cd-572870cea918)![则](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/270826a2-02d6-40aa-b526-8f200d7539a4)
游ゴシック的“小少肖”
![小](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/f922a17f-d02b-45fb-9113-3d4578f0a210)![少](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/21a25fdf-36ac-46d0-a2c8-c5fdab483169)![肖](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/58043328/397ef49b-cf52-47e1-9b62-0220eb7677b0)
西文里这样的例子就更多了。

----

黑体倒不是必须一道笔画头尾粗细一致，可以参考Saltillo这个拉丁字母 u+a78b [ꞌ] / u+a78c [Ꞌ]
> Many alphabets use it to represent glottal occlusion or glotal stop phoneme. Saltillo and apostrophe have different Unicode points and functional categories, one is a letter and the other is a punctuation mark, this discrepancy causes conflicts in the digitization of texts.

在有这个字的黑体中都不是一根短竖杠，而𚿵就像2个ꞌ上下镜像对接，或者说𚿳的掰直形态，以便与㇑、丨区分。当然，我可以再制作一种细端增粗的版本。

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
第一个能明白你所说的视觉修正问题，但你上面那个字显然是修正过度了（至少我看起来像是这么回事）。
***
至于说变态假名B的问题我已经明晰了，但是考虑到你现在所制作的这个版本确乎是有点太不像黑体了（至少我是这么觉得的），所以也劳烦你制作一种细端增粗的版本了。

**Comment by MY1L** [comment]
关于2023年12月19日的意见已收到，我之后一并制作。

关于2023年11月7日的：
> ①U+2FFF“⿿”、②U+31EF“㇯”
> 目前的Release最新版的遍黑体中，这两个形态已经弃用了，下个版本会跟进成和码表相同，即如此： [QQ截图20231107211701](https://private-user-images.githubusercontent.com/82664718/281052771-a4b5d416-ceb1-4ffd-a2a0-15087f84771d.png) [QQ截图20231107211857](https://private-user-images.githubusercontent.com/82664718/281053015-fa45eec6-ed63-4e74-a5b2-8f03e49e8351.png) 两个形态均择自[隙间黑体](https://oppekebekkanko.booth.pm/items/2117070)。 考虑到你的字体对这两个字符所制作的样式与我的字体风格差异较大，故不采用。

刚好[我前天补充了思源宋/码表用字体](https://github.com/unicode-org/cjk-symbols/issues/3#issuecomment-1906204188)的⿼⿽⿾⿿㇯，又刚好思源宋的这些箭头和虚线框符号与思源黑没啥差别：
![image](https://github.com/unicode-org/cjk-symbols/assets/58043328/ece15cf4-1ef9-4c27-9368-a285168c3e1c)
[CJKSymbolsPatch2.zip](https://github.com/unicode-org/cjk-symbols/files/14025378/CJKSymbolsPatch2.zip)
> CJKSymbolsPatch2glyphs-SrcHanSe-Regular.otf — intended to Source
> CJKSymbolsPatch2.ttf — intended to PDF

那么现在字形风格也一致了。
