### ISSUE TITLE
关于遍黑体对IVD的支持

### ISSUE THREAD

**Issue by hemoumouda** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project#19]
想询问一下是否已经/将来考虑对本字体IVD的制作,或者已经制作完成了？
例如 辻+\ue0100=<img src="https://ziphoenicia-1300189285.cos.ap-shanghai.myqcloud.com/code_chart_14/%E8%BE%BB_J.svg" width="19" height="19">

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
目前暂无这方面的打算，抱歉。
