### ISSUE TITLE
一些字符显示错误，如图

### ISSUE THREAD

**Issue by duyraven** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project#20]
![IMG_20240124_162411](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/54952917/066b7531-eeab-4a73-9e30-8abc22eebfa2)

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
我这边核对了一下，两个字符均是没有问题的，烦请核实一下是不是您那边设备或者是输入法的字体显示出了问题。
![QQ截图20240124182318](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/82664718/e4e91a87-123e-4a0e-bb2a-bb34cc37fce0)![QQ截图20240124182453](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/82664718/e9c191ef-422d-4ffb-a494-fbc4f90320c7)
