### ISSUE TITLE
"𰁙“（30059）的字形错误

### ISSUE THREAD

**Issue by j1g5awi** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project#21]
![图片](https://github.com/Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project/assets/50312681/8e6c3f67-2ba5-470f-bd44-a6345fcbdc98)

如图

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
收到，感谢反馈，下一版本中将会修复这个问题。
