### ISSUE TITLE
𫖉：错形，𣅏民：未知轮廓问题

### ISSUE THREAD

**Issue by JxIIIII** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project#26]
**𫖉：** 错形

![bug_A](https://github.com/user-attachments/assets/5e1d8fbd-9142-44a0-b804-0af565256910)

**𣅏民：** 未知轮廓问题

![bug_B](https://github.com/user-attachments/assets/f9445556-b671-47d4-8de4-4952532a0ced)

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
第一个字将在下一个版本修复。后两个字经排查，未发现你图中所提到的问题。

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
第一个字将在下一个版本修复。后两个字经排查，未发现你图中所提到的问题。
