### ISSUE TITLE
可否申請提交到 Google Fonts？

### ISSUE THREAD

**Issue by laubonghaudoi** [Fitzgerald-Porthmouth-Koenigsegg/Plangothic-Project#27]
目前Google Fonts 非常缺少收字全的繁體中文字型。只要參照這裏的步驟，去Google Fonts官方repo裏開一個issue就能提交 https://googlefonts.github.io/gf-guide/onboarding.html

**Comment by laubonghaudoi** [comment]
原來是這樣，我回去聯繫一下 Google Fonts 看能不能加速

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
> [有人交過了](https://github.com/google/fonts/issues/4746)，現在貼著「Needs manager's opinion」標籤。

我已做了回复，但不知为何之后没了消息，是我的回复方式有误（英语白痴）？

**Comment by Fitzgerald-Porthmouth-Koenigsegg** [comment]
> @Fitzgerald-Porthmouth-Koenigsegg Dave 在 [google/fonts#4746 (comment)](https://github.com/google/fonts/issues/4746#issuecomment-1146620286) 説
> 
> > do you have any suggestions how this can be integrated upstream?
> 
> 意思就是説，既然這個項目是思源黑體的補充，他想問你有沒有考慮過直接把字體加入上游 Adobe 的 Source Han Sans 裏，就是這個 https://github.com/adobe-fonts/source-han-sans
> 
> Dave 應該是一直在等你對他這個問題的回覆，所以才一直沒有消息。如果想加速的話最好還是和他討論清楚一下比較好，如果你英文不夠好的話可以用 Google Translate 來幫忙？我個人認為如果能把字型直接加進上游的話，可能效果會最理想，因為 Noto Sans 是 Google 第一方字型，用户能直接用到，不需要再安裝第三方的遍黑體。
> 
> 據我瞭解，Google Fonts對外部提交的字型質量門檻很高，會要求字型作者對字型持續維護以及做要求的相應改動。例如他們會要你提供該字型的所有源 .ufo 或者 .glyph 文件，以及構建一個 build system等等，所以要麻煩你做好這些準備。如果沒有提供 .ufo 或者 .glyph 的話他們是不會接收的。可以參考目前的成功案例 https://github.com/MoonlitOwen/ChocolateSans
> 
> 還有一件事情是，目前 README 上面寫
> 
> > 该字体目前处于未完成阶段，仍然缺少大量汉字。
> 
> 可能要解釋一下具體是缺哪個區的哪些漢字比較好，因為 Google Fonts 需要作者保證持續維護，如果看見是個爛尾項目的話可能會不𫖸意收。

大概明白是怎么回事了，应该不是我没说明白的问题。
这个项目肯定不会烂尾，但是它不可能做到跟进的非常快，因为我现实生活中事务实在是太多，做字体并不是我的主业，其次关于你提到的.ufo或者.glyph文件，以及構建一個build system这块完全是我的知识盲区，亦完全没有听说过这种东西，无暇去准备这些方面。

**Comment by laubonghaudoi** [comment]
.ufo 就是像 https://github.com/MoonlitOwen/ChocolateSans/tree/main/source/ChocolateClassicalSans-Regular.ufo 這裡一個文件，UFO全稱是 [Unified Font Object](https://en.wikipedia.org/wiki/Unified_Font_Object)，是一個公開字型標準化文件格式。因為現代軟件工程需要對字體裏的每個字型進行跟蹤和版本控制，從而方便軟件開發，所以不能單純一個 ttf 文件這樣放上去直接用，Google 需要這種「精確到每個字元的版本記錄」。
